### ISSUE TITLE
Just a heads up

### ISSUE THREAD

**Issue by MrTarantula** [MetacoSA/NBitpayClient#14]
https://support.bitpay.com/hc/en-us/articles/360000502006-Overview-of-Upcoming-BitPay-API-Changes-May-7-2018-

Not listed there is the change to `InvoiceData.PayoutPercentage`, which broke my app. It's now an object:

```json
"payoutPercentage": { "USD": 100 }
```

**Comment by NicolasDorier** [comment]
Shit :(

Will fix this today.

**Comment by NicolasDorier** [comment]
Can you test the new package I just pushed and close if it fix your issue?

**Comment by MrTarantula** [comment]
I'm using the official BitPay client, but that's exactly how I modified it and it works. Closing.
