### ISSUE TITLE
Refund APIs and invoice properties missing

### ISSUE THREAD

**Issue by kspearrin** [MetacoSA/NBitpayClient#18]
https://bitpay.com/api#resource-Invoices

Looks like the `refundInfo` property is missing from an the invoice object.

Also, I am not seeing a way to execute the `* /invoices/:invoiceId/refunds` API endpoints.

**Comment by NicolasDorier** [comment]
Would be nice to have it.

**Comment by kspearrin** [comment]
#20 adds missing `refundInfo` array.

**Comment by NicolasDorier** [comment]
Closing this as #20 should have fixed it
