### ISSUE TITLE
The Official BitPay now fully updated and available on its repo and NuGet

### ISSUE THREAD

**Issue by anbugal** [MetacoSA/NBitpayClient#23]
In the past few weeks at BitPay we have been taking care of our SDKs and we have released a completely updated and improved version which is available in its own repos and also as a quick accesible package on NuGet.

Thank you so much for offering your solution openly and we appreciate the effort.
I would kindly ask to update your README as the official project is now fully usable and stable.

We will also be releasing updates periodically as well as for the rest of the supported languages and plugins.

Once again thank you for your support and we invite you to participate on the official and open source SDK.

**Comment by NicolasDorier** [comment]
Done! Thanks you.
