### ISSUE TITLE
token parsing bug

### ISSUE THREAD

**Issue by mrtristan** [MetacoSA/NBitpayClient#26]
in `public AccessToken GetAccessToken(Facade requirement)`, in the case of `_Tokens` containing just a `pos` token, and if a `pos` token is requested, the second `if` here will cause the token resolution to return null.

![image](https://user-images.githubusercontent.com/1546181/72691335-8b319300-3af2-11ea-964e-cfdeacc307b2.png)

i'd propose that this can be shortened to the following which will achieve what you're trying to do with this fallback/inheritance concept:

![image](https://user-images.githubusercontent.com/1546181/72691421-3b070080-3af3-11ea-977b-a16e11a7d1b1.png)

additionally, it should use the token that was explicitly requested if present so starting it off with a null check to make sure the initial lookup attempt failed.

sending up a PR

**Comment by mrtristan** [comment]
@NicolasDorier if you get a chance to merge this and bump the package, that'd be appreciated. I'll need to set up consuming my fork otherwise so hoping I don't have to. 🤞

**Comment by NicolasDorier** [comment]
Thank you pushed new version. 1.0.0.36

**Comment by mrtristan** [comment]
appreciate the quick turnaround
